[workspace]
members = [
	"colvec",
	"colvec-derive", "tests/test-nightly_off-std_off", "tests/test-nightly_off-std_on", "tests/test-nightly_on-std_off", "tests/test-nightly_on-std_on",
]
resolver = "2"
